services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'
    networks:
      - observability
    restart: unless-stopped
  loki:
    image: grafana/loki:3.6.6
    container_name: loki
    user: root
    command:
      - '-config.file=/etc/loki/loki.yaml'
      - '-target=all'
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/loki
      - loki-wal:/wal
    ports:
      - '3100:3100'
    networks:
      - observability
    restart: unless-stopped
  tempo:
    image: grafana/tempo:2.10.1
    container_name: tempo
    command:
      - '-config.file=/etc/tempo/tempo.yaml'
      - '-target=all'
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo
      - tempo-metrics-storage:/var/tempo/metrics-storage
    ports:
      - '3200:3200'
      - '4317:4317'
      - '4318:4318'
    networks:
      - observability
    restart: unless-stopped
  trace-gen:
    build:
      context: .
      dockerfile: Dockerfile.trace-gen
    container_name: trace-gen
    depends_on:
      - tempo
    networks:
      - observability
    restart: unless-stopped
  jaeger-ui:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger-ui
    ports:
      - '16686:16686'
    environment:
      QUERY_BASE_PATH: /
      QUERY_PORT: "16686"
    command:
      - --query.grpc.host=tempo
      - --query.grpc.port=4317
    networks:
      - observability
    restart: unless-stopped
    depends_on:
      - tempo

volumes:
  prometheus-data:
  loki-data:
  loki-wal:
  tempo-data:
  tempo-metrics-storage:
